export const ACCOUNT_SETTINGS_INIT = 'ACCOUNT_SETTINGS_INIT';
export const ACCOUNT_SETTINGS_SUBMIT_SUCCESS = 'ACCOUNT_SETTINGS_SUBMIT_SUCCESS';

export const GET_BUILD_FLOW_LISTS_SUCCESS = 'GET_BUILD_FLOW_LISTS_SUCCESS';
export const GET_BUILD_FLOW_LISTS_ERROR = 'GET_BUILD_FLOW_LISTS_ERROR';
export const GET_APP_LISTS_SUCCESS = 'GET_APP_LISTS_SUCCESS';
export const GET_APP_LISTS_ERROR = 'GET_APP_LISTS_ERROR';
